---
general:
  buildTool: "npm"
  containerRegistryUrl: https://concise.common.repositories.cloud.sap
  # chartPath: charts/sustainable-saas
service:
  buildToolVersion: "N18"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
  Acceptance:
    cloudFoundryDeploy: false
    npmExecuteEndToEndTests: false
    kubernetesDeploy: false
    chartPath: charts/sustainable-saas
  Compliance:
    sonarExecuteScan: false
  Release:
    cloudFoundryDeploy: false
    tmsUpload: false
    kubernetesDeploy: true
    chartPath: charts/sustainable-saas
    forceUpdates: false # custom defaults
    additionalParameters:
      - --debug
      - --set
      - global.imagePullSecret.name=concise
    deployTool: helm3
    deploymentName: mh-deployment-01
    kubeConfigFileCredentialsId: kube-config
    stashContent:
      - source
      - buildResult
    verbose: true
    namespace: mh-01
    helmDeployWaitSeconds: 300
    valuesMapping:
      api.image.repository:    image.susaas_image/susaas_api.repository
      api.image.tag:           image.susaas_image/susaas_api.tag
      srv.image.repository:    image.susaas_images/susaas_srv.repository
      srv.image.tag:           image.susaas_images/susaas_srv.tag
      broker.image.repository: image.susaas_image/broker.repository
      broker.image.tag:        image.susaas_image/broker.tag
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"

  buildExecute:
    npmRunScripts: [ 'cds-build' ]
    npmInstall: false
    cnbBuild: true
    helmExecute: true

  pipelineStashFilesAfterBuild:
    stashIncludes:
      buildResult: '**/*'

  cnbBuild:
    dockerConfigJsonCredentialsId: docker-config
    multipleImages:
      - path: gen/srv
        containerImageName: susaas-images/susaas-srv
      - path: gen/api
        containerImageName: susaas-image/susaas-api
      - path: broker
        containerImageName: susaas-image/broker
      - path: gen/db-com
        containerImageName: susaas-image/susaas-db-com

  helmExecute:
    # the template delimeters here are a workaround. We are forced to use a values.yaml-preprocessing which fails in our
    # case when we have the defaults ( {{}} ). There is this PR: https://github.com/SAP/jenkins-library/pull/4511 for opting-out from the preprocessing
    helmCommand: dependency
    dependency: update
    stashContent:
      - source
    # should be provided finally in the general section in order not to have the twice. Does not work at the moment
    # since chartPath is not / was not labeled with GENERAL
    chartPath: charts/sustainable-saas
    templateStartDelimiter: '[['
    templateEndDelimiter: ']]'

  dockerExecuteOnKubernetes:
    # should be removed finally
    verbose: true
