---
general:
  buildTool: "npm"
  containerRegistryUrl: https://concise.common.repositories.cloud.sap
  # the chartPath will be activated in general once piper PRs are merged
#  chartPath: charts/sustainable-saas
service:
  buildToolVersion: "N18"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
  Acceptance:
    cloudFoundryDeploy: false
    npmExecuteEndToEndTests: false
    kubernetesDeploy: false
    # this is where the configuration would go for a kubernetesDeploy during the Acceptance stage
  Compliance:
    sonarExecuteScan: false
  Release:
    cloudFoundryDeploy: false
    tmsUpload: false
    kubernetesDeploy: true
    # the chartPath will be moved to general once piper PRs are merged
    chartPath: charts/sustainable-saas
    # here is the configuration for a kubernetesDeploy during the Release stage
    additionalParameters:
      # we should keep the debug flag. Otherwise there is not much written to the log during deployment. That look like we are stuck.
      - --debug
      - --set
      - global.imagePullSecret.name=concise
    # we will currently only offer helm3, not kubectl deployTool. So this is static.
    deployTool: helm3
    deploymentName: mh-deployment-01
    kubeConfigFileCredentialsId: kube-config
    namespace: mh-01
    valuesMapping:
      api.image.repository: image.susaas_image/susaas_api.repository
      api.image.tag: image.susaas_image/susaas_api.tag
      srv.image.repository: image.susaas_images/susaas_srv.repository
      srv.image.tag: image.susaas_images/susaas_srv.tag
      broker.image.repository: image.susaas_image/broker.repository
      broker.image.tag: image.susaas_image/broker.tag

    ## VV PUT THESE INTO CUSTOM DEFAULTS IN PIPELINE-LIB VV##
    # The source stash is required for the deployment (... values.yaml, Chart.yaml)
    # the build result stash should have the updated chart dependencies
    forceUpdates: false # custom defaults
    stashContent: # custom defaults
      - source # custom defaults
      - buildResult # custom defaults
    ## ^^ PUT THESE INTO CUSTOM DEFAULTS IN PIPELINE-LIB ^^##

steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"

  # custom additions to make npm build work
  buildExecute:
    npmRunScripts: [ 'cds-build' ]
    npmInstall: false
    cnbBuild: true
    helmExecute: true

  ## VV PUT THESE INTO CUSTOM DEFAULTS IN PIPELINE-LIB? VV##
  pipelineStashFilesAfterBuild:
    stashIncludes:
      # should be more finegrain finally, the important thing is that the chart dependencies needs to be contained
      # in this stash (**/charts/*.tgz). The build results stash is handed over to kubernetesDeploy. Inside
      # kubernetesDeploy we need the templates, value files and the charts. Everything but the chart dependencies
      # is already contained in the source stash
      buildResult: '**/*'
  ## ^^ PUT THESE INTO CUSTOM DEFAULTS IN PIPELINE-LIB ^^##

  cnbBuild:
    dockerConfigJsonCredentialsId: docker-config
    multipleImages:
      - path: gen/srv
        containerImageName: susaas-images/susaas-srv
      - path: gen/api
        containerImageName: susaas-image/susaas-api
      - path: broker
        containerImageName: susaas-image/broker
      - path: gen/db-com
        containerImageName: susaas-image/susaas-db-com
    # containerImageTag is optional. When not provided, this means a guid prepared by artifactSetVersion will be used

  helmExecute:
    helmCommand: dependency
    dependency: update
    stashContent:
      - source
    # the chartPath will be moved to general once piper PRs are merged
    chartPath: charts/sustainable-saas
    ## VV PUT THESE INTO CUSTOM DEFAULTS IN PIPELINE-LIB VV##
    # the template delimeters will be removed once piper PRs are merged. Another flag will take it's place- this can go in custom defaults?
    templateStartDelimiter: '[['
    templateEndDelimiter: ']]'
    ## ^^ PUT THESE INTO CUSTOM DEFAULTS IN PIPELINE-LIB ^^##

  dockerExecuteOnKubernetes:
    # should be removed for final version
    verbose: true
