---
general:
  buildTool: "npm"
  containerRegistryUrl: https://concise.common.repositories.cloud.sap
  chartPath: charts/sustainable-saas
  dockerConfigJsonCredentialsId: docker-config
  verbose: true
service:
  buildToolVersion: "N18"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
  Acceptance:
    npmExecuteEndToEndTests: false
    kubernetesDeploy: false
    # this is where the configuration would go for a kubernetesDeploy during the Acceptance stage
#    additionalParameters:
#      - --debug
#      - --set
#      - global.imagePullSecret.name=concise
#    deploymentName: mh-deployment-01
#    kubeConfigFileCredentialsId: kube-config
#    namespace: mh-01
  Compliance:
    sonarExecuteScan: false
  Release:
    kubernetesDeploy: true
    containerRegistrySecret: concise
    additionalParameters:
      # we should keep the debug flag. Otherwise there is not much written to the log during deployment. That look like we are stuck.
      - --debug
#      - --set
#      - global.imagePullSecret.name=concise
    deploymentName: mh-deployment-044
    kubeConfigFileCredentialsId: kube-config
    namespace: mh-01
    valuesMapping:
      global.imagePullSecret.name: imagePullSecrets[0].name

steps:
  # custom additions to make npm build work
  buildExecute:
    npmRunScripts: [ 'cds-build' ]
    npmInstall: false
    cnbBuild: true
    helmExecute: true

  cnbBuild:
    multipleImages:
      - path: gen/srv
        containerImageName: susaas-images/susaas-srv
      - path: gen/api
        containerImageName: susaas-image/susaas-api
      - path: broker
        containerImageName: susaas-image/broker
      - path: gen/db-com
        containerImageName: susaas-image/susaas-db-com
    # containerImageTag is optional. When not provided, this means a guid prepared by artifactSetVersion will be used

  helmExecute:
    helmCommand: dependency
    dependency: update

  kubernetesDeploy:
    valuesMapping:
      api.image.repository: image.susaas-image/susaas-api.repository
      api.image.tag: image.susaas-image/susaas-api.tag
      srv.image.repository: image.susaas-images/susaas-srv.repository
      srv.image.tag: image.susaas-images/susaas-srv.tag
      broker.image.repository: image.susaas-image/broker.repository
      broker.image.tag: image.susaas-image/broker.tag
#      global.imagePullSecret.name: imagePullSecrets[0].name

  dockerExecuteOnKubernetes:
    # should be removed for final version
    verbose: true
