{{ if .Values.expose.enabled}}
{{- $onboardingHost := printf "%s.%s.svc.cluster.local" ( default ( printf "%s-%s" .Release.Name "router" ) .Values.global.router.fullName ) .Release.Namespace -}}
{{- $applicationHost := printf "%s.%s.svc.cluster.local" ( printf "%s-%s" ( default "susaas" .Values.global.saasRelease ) (default "router" .Values.global.saasRouter)) .Release.Namespace -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ printf "%s-%s" ( default "susaas" .Values.global.saasRelease ) ( uuidv4 | trunc 5) }}
  labels: {{- include "obd-router.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ .Values.global.gateway | default "kyma-system/kyma-gateway"  }}
  hosts:
    # Application domain like susaas.sap-demo.com
    - {{ printf "%s-%s.%s" ( default "susaas" .Values.global.saasRelease ) .Release.Namespace .Values.global.domain }}
    # Onboarding domain like onboarding-susaas.sap-demo.com
    - {{ printf "onboarding-%s-%s.%s" ( default "susaas" .Values.global.saasRelease ) .Release.Namespace .Values.global.domain }}
  http:

    # Handler for all requests targeting the SaaS application
    - match:
      - uri:
          regex: ^.*(sapsusaasuipublic|sapsusaasuiadmin).*$
        headers:
          Cookie:
            regex: ^.*(x-custom-host=).*$
      - uri:
          regex: ^.*(login).*$
        queryParams:
          authType:
            exact: xsuaa
      route:
        - destination:
            host: {{ $applicationHost }} 
            port:
              number: 5000
          weight: 100
      timeout: 30s
    
    # Handler for the onboarding application ensuring a domain switch
    - match:
      - uri:
          regex: ^.*(sapsusaasuionboarding).*$
        authority:
          exact: {{ printf "%s-%s.%s" ( default "susaas" .Values.global.saasRelease ) .Release.Namespace .Values.global.domain }}
      redirect:
        authority: {{ printf "onboarding-%s-%s.%s" ( default "susaas" .Values.global.saasRelease ) .Release.Namespace .Values.global.domain }}
    
    # Handler for all requests targeting the onboarding router/apps
    - match:
      - uri:
          regex: ^.*(login|sapsusaasuihome|sapsusaasuionboarding).*$
      route:
        - destination:
            host: {{ $onboardingHost }}  
            port:
              number: 5000
          weight: 100
      timeout: 30s

    # Handler for all other requests
    - match:
      - uri:
          regex: .*
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ $onboardingHost }}  
            port:
              number: 5000
          weight: 100
      timeout: 30s
{{ end }}